name = "SQLSketch"
uuid = "b3e6e9d0-8c4e-4f3a-9d8e-9f5e6d7c8b9a"
authors = ["daikichbia9511 <daikichiba.tech.ml@gmail.com>"]
version = "0.1.0"

[deps]
# Phase 4: Driver abstraction
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
# Phase 5: Dates, UUIDs (to be added)

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[targets]
test = ["Test", "Tables"]
