name = "SQLSketch"
uuid = "b3e6e9d0-8c4e-4f3a-9d8e-9f5e6d7c8b9a"
version = "0.1.0"
authors = ["daikichbia9511 <daikichiba.tech.ml@gmail.com>"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LibPQ = "194296ae-ab2e-5f79-8cd4-7183a0a5a0d1"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
BenchmarkTools = "1.6.3"
DataStructures = "0.19.3"
Documenter = "1.16.1"
DocumenterTools = "0.1.21"
JET = "0.11"
LRUCache = "1.6.2"
julia = "1.12"

[extras]
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Tables"]
